dist: xenial
sudo: required
language: generic

branches:
    - master
notifications:
  email:
    recipients:
      - gusbemacbe@gmail.com
      
addons:
  apt:
    packages:
      - xmlstarlet

script:
    - make -k test-all
