name: Travis

on:
  pull_request:
  push:
    branches:
      - gusbemacbe

jobs:
  run_tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Install xmlstarlet
      run: sudo apt-get install xmlstarlet
    - name: Run tests
      run: make -k test-all
      
notifications:
  email:
    recipients:
      - gusbemacbe@gmail.com
